# main config to train your model
# check default.config for all available options

project_name: YOUR_PROJECT_NAME       # Used for WANDB
version_name: UNETv1               # Make run unique by changing this counter

# main model:
precision: 32
epoch: 100
batch_size: 2
acc_grad_batches: 4
module: LightningAE

# generator
generator: UNet3D
g_pooling_type: full_conv
g_filters: [64, 128, 256, 512, 1024]
# g_activation: ReLU
g_optimizer: Adam
g_lr: 1e-4
#lr_scheduler: 'exponential_decay_0.01'
g_loss: MeanAbsoluteError

# data:
data_split_pkl: Data/data_5fold.pickle       # inside data folder .json or .pickle
data_generator: CustomDataLoader
data_folder: Data/data_noblur_25_64x64x64    # inside project dir
pet_normalization_constant: 32676
augment: True
data_shape: [128, 128, 128]
color_channels_in: 1
repeat_patient_list: 100

# for plotting during training
callback_image2image: 'ImagePredictionLogger'

# model-specific info (self-generated) - do not write anything beyond here
