# main config to train models
project_name: YOUR_PROJECT_NAME       # Used for WANDB
version_name: RESUNETv1               # Make run unique by changing this counter

# main model:
precision: 32
epoch: 100
batch_size: 2
acc_grad_batches: 4
module: LightningAE

# generator
generator: Res3DUnet
# g_activation: ReLU
g_optimizer: Adam
g_lr: 1e-4
#lr_scheduler: 'exponential_decay_0.01'
g_loss: MeanAbsoluteError
# pretrained_generator: absolute path to .pt or .ckpt

# discriminator - will be used if model is GAN
# discriminator: ConvNetDiscriminator
# d_optimizer: Adam
# d_lr: 2e-4
# d_loss: BCEWithLogitsLoss

# data:
data_split_pkl: Data/data_5fold.pickle       # inside data folder .json or .pickle
data_generator: CustomDataLoader
data_folder: Data/data_noblur_25_64x64x64    # inside project dir
pet_normalization_constant: 32676
augment: True
data_shape: [64,64,64]
color_channels_in: 1
repeat_patient_list: 500

# for plotting during training
callback_image2image: 'ImagePredictionLogger'

# model-specific info (self-generated) - do not write anything beyond here
